# Generated by Django 5.2.4 on 2025-11-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('student', 'Student'), ('team', 'Team')], default='free', max_length=50)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('total_pdfs_processed', models.PositiveIntegerField(default=0)),
                ('total_words_processed', models.PositiveIntegerField(default=0)),
                ('total_pages_processed', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Extra',
                'verbose_name_plural': 'User Extras',
            },
        ),
    ]
