# Generated by Django 5.2.4 on 2025-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_processeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
    ]
