# Generated by Django 5.2.4 on 2025-11-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_processeddocument_generated_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
