# Generated by Django 5.2.4 on 2026-01-14 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_document_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content of the message')),
                ('is_user', models.BooleanField(default=True, help_text='True if user sent, False if AI')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('summary', 'Summary'), ('question', 'Question'), ('key_points', 'Key Points')], default='text', help_text='Type of message: text, summary, question, key points, etc.', max_length=50)),
                ('order', models.PositiveIntegerField(blank=True, help_text="Sequential order of the message in this document's chat", null=True)),
                ('is_processed', models.BooleanField(default=True, help_text='If the AI response is fully processed')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete message, hidden from user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
                ('document', models.ForeignKey(help_text='The document/chat session to which this message belongs', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.document')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent the message; null if sent by AI', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
